services:
  ollama:
    build: .
    container_name: ollama
    deploy:
      resources:
        reservations:
          # will get skipped if you dont have these resources
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    ports:
      - '11434:11434'
    volumes:
      - ollama:/root/.ollama
    healthcheck:
      test: ['CMD', 'bash', '-c', "ollama list | grep -q 'summarization-model'"]
      interval: 5s
      retries: 5
      start_period: 25s
      timeout: 5s

volumes:
  ollama:
